### ISSUE TITLE
Trigger "from_state" returning blank string

### ISSUE THREAD

**Issue by dallas6672** [Snuffy2/places#49]
Was running into issues when trying to use "trigger.event.data.from_state" in some automations. Noticed that it was coming back blank sometimes and other times the string was cutoff.  Appears to be related to Line 582...

`previous_state = self.state[:-14] `

I would also think that it would cause Line 1146 to always evaluate True unless I'm overlooking something...

`if previous_state != new_state:`

**Comment by Snuffy2** [comment]
Good catch. That truncate was leftover from old code and I missed it. Thanks
v1.13.5.3 should fix it
