### ISSUE TITLE
Feature Request/Suggestion

### ISSUE THREAD

**Issue by dallas6672** [Snuffy2/places#59]
In case you were interested, I thought I'd share two things that I started adding to your component.

Option to use OSM Map Link instead of Apple or Google.
Set configuration.yaml to "map_provider: osm"

Line 521 (below the other maplinks) I added...
```            
            maplink_osm = None
```

Inserted the URL at Line 562...
```
            # OSM maplink
            maplink_osm = (
                "https://www.openstreetmap.org/?mlat="
                + new_latitude + '&mlon=' + new_longitude + '#map=' + self._map_zoom + '/' + new_latitude[:8] + '/' + new_longitude[:9]
            )
```

Line 727 Replaced the existing If Else statement for setting map_link...
```
            if self._map_provider == "google":
                self._map_link = maplink_google
            elif self._map_provider == 'apple':
                self._map_link = maplink_apple
            else:
                self._map_link = maplink_osm
```
#
#
#
#
 Also, added tracking the previous Place Name. Nice to have for an automation that triggers when you leave a certain place. (trigger.event.data.from_place_name)
 
 Line 550 (below setting previous_location and home_location)...
 ```            
             previous_place_name = self._place_name
 ```
 
 Line 1181 added this to the event_data
 ```            
             event_data["from_place_name"] = previous_place_name
 ```

**Comment by Snuffy2** [comment]
Definitely like the OSM Map Link option and will add that.  ([See branch](/Snuffy2/places/tree/Add-OSM-Map-Link-Option), will put into a release soon)

I'm curious as to the use of previous_place_name? 
- How is this better than trigger.from_state in an automation?
- Personally, if I were to make use of this, I'd actually make previous_place_name show the zone name if they were in a zone or place_name if they were in a place.
- My device_trackers update pretty frequently, especially when driving. Many of the locations are addresses and don't have a place_name. Thus, the previous_place_name would become blank or be replaced with a different place_name pretty quickly after leaving said place. That wouldn't affect using it as a trigger in an automation. But, would there be more value if the previous_place_name persisted across multiple location updates until a new location is a zone or has a place_name? That way it would never be blank.

**Comment by dallas6672** [comment]
What I noticed from using the triggers is that "trigger.from_state" already works for Zones. Once you enter a Zone that becomes the State. Difference with the Place Name is that when it's the "to_state" or "from_state", it also has other County, City or address information appended to it, and not just the Place Name itself.

It could definitely make it easier to also have the from_zone also. For me I just use the following template condition to see if I left a Zone. If this evaluates True, then I know I just left a Zone... 
```
{% set zones = states.zone | map(attribute='name') | list %}
{{ trigger.event.data.from_state in zones }}
```

So, if the from_zone was added it would keep me from having to check it against the Zone list and would be able to know it was a Zone as long as the from_zone wasn't blank or None.


For my current uses, I wouldn't need the Place Name to persist, but can't speak for others


Thanks

**Comment by Snuffy2** [comment]
What if the last_place_name also factored in zone in addition to place? It would show the last zone name or place name in a single attribute. Would that break how you use it?

**Comment by dallas6672** [comment]
I would have to change the automation slightly, but that's not a problem. It would save me from having to check different trigger event values. Instead of having to check if "from_state" is a Zone and checking the value of "previous_place_name ", all I would have to check against is your new "last_place_name"

**Comment by dallas6672** [comment]
Just a thought. Depending on how the "last_place_name" is used in someone's automation, they could have issues with the automation triggering multiple times when the "last_place_name" persist beyond a single update. If someone has a trigger when "last_place_name" equals a specific place name or Zone, then that automation will trigger on every location update until the "last_place_name" changes.

To keep this from happening they will also need to do something like this for a condition...

`
{{ trigger.event.data.last_place_name in trigger.event.data.from_state }}
`

**Comment by Snuffy2** [comment]
Good point. What if I make it so the last_place_name attribute persists but in the event, the last_place_name will only show if it is different from previous? Or do you think should I not make it persist at all?

**Comment by dallas6672** [comment]
Hard to say since I can't personally think of a use case for it. The work around for having it persist is easy with something like the previously mentioned template. But if someone is needing it to persist then the work around would require making custom edits to the component or adding an input Helper.

When you say "the last_place_name will only show if it is different from previous", are you referring to the Entity State Attributes? If so, what about making the Attribute persist until the name is different, but make it not persist for the trigger event data?

**Comment by Snuffy2** [comment]
> When you say "the last_place_name will only show if it is different from previous", are you referring to the Entity State Attributes? If so, what about making the Attribute persist until the name is different, but make it not persist for the trigger event data?

Yes, I think that's the same as what I was saying. Persist last_place_name for the attribute in the sensor. For the event data, only show if the last_place_name changes.

**Comment by dallas6672** [comment]
> 

Sounds good. Thanks

**Comment by Snuffy2** [comment]
Let me know if this is working for you in v1.13.6

**Comment by dallas6672** [comment]
Started getting this in the error logs...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 490, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 902, in do_update
    if city.startswith("City of"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by dallas6672** [comment]
Have updated my automations to use the new "last_place_name" and it has triggered correctly with no issues today.

Thanks
